os: linux
dist: bionic
language: php

php:
    - 7.4

cache:
    directories:
        - $HOME/.composer/cache/files

env:
    - COMPOSER_VERSION=2
      DOCKER_COMPOSE_VERSION=1.27.4

before_install:
    - sudo apt-get -y remove docker docker-engine docker.io containerd runc
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - sudo apt-get update
    - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce docker-ce-cli containerd.io
    - docker --version
    - sudo rm /usr/local/bin/docker-compose
    - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin
    - |
        if [ "$TRAVIS_BRANCH" != "master" ] && [ "$TRAVIS_BRANCH" != "develop" ]; then
            composer config extra.branch-alias.dev-$(git rev-parse HEAD) 0.1.x-dev
        fi

jobs:
    include:
        -
            stage: Bundle tests
            install:
                - composer install --no-interaction
                - |
                    if [ "$TRAVIS_BRANCH" != "master" ] && [ "$TRAVIS_BRANCH" != "develop" ]; then
                        composer update --lock
                    fi
                - echo 'DATABASE_URL=mysql://test:test@mysql:3306/numbernine_test?serverVersion=5.7' > .env.test.local
                - mkdir -p var/cache
                - mkdir -p public/uploads
                - chmod -R 0777 var
                - chmod -R 0777 public
                - docker-compose up -d
            script:
                - ./vendor/bin/grumphp run --no-interaction
                - docker-compose exec php vendor/bin/phpunit

        -
            stage: New project Docker installation
            install:
                - cd ..
                - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/numberninecms/numbernine/master/installer | bash -s newproject -v"
                - cd newproject
                - rm -rf vendor/numberninecms/cms
                - cp -R ../cms vendor/numberninecms/cms
                - sed -i "s/1000:1000/$(id -u):$(id -g)/" docker/docker-compose.yaml
            script:
                - bin/console numbernine:docker:install -v --no-interaction
                - wget --spider --no-check-certificate https://localhost:443/
