#
# This file builds a test environment for running functional tests
#

version: "3.8"

services:
    php:
        image: numberninecms/php:8.1-fpm-dev
        working_dir: /var/www/html
        user: '1000:1000'
        restart: 'no'
        volumes:
            - ./:/var/www/html
            - ./docker/symfony.ini:/etc/php81/conf.d/symfony.ini

    mysql:
        image: mysql:8
        restart: 'no'
        environment:
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=numbernine_test
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
