<?php

/*
 * This file is part of the NumberNine package.
 *
 * (c) William Arin <williamarin.dev@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace NumberNine\Bundle;

use DAMA\DoctrineTestBundle\DAMADoctrineTestBundle;
use Doctrine\Bundle\DoctrineBundle\DoctrineBundle;
use Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle;
use Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle;
use FOS\JsRoutingBundle\FOSJsRoutingBundle;
use NumberNine\ChapterOne\NumberNineChapterOneBundle;
use Stof\DoctrineExtensionsBundle\StofDoctrineExtensionsBundle;
use Symfony\Bundle\FrameworkBundle\FrameworkBundle;
use Symfony\Bundle\FrameworkBundle\Kernel\MicroKernelTrait;
use Symfony\Bundle\SecurityBundle\SecurityBundle;
use Symfony\Bundle\TwigBundle\TwigBundle;
use Symfony\Cmf\Bundle\RoutingBundle\CmfRoutingBundle;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
use Symfony\Component\HttpKernel\Kernel;
use Symfony\Component\Routing\Loader\Configurator\RoutingConfigurator;
use Symfony\WebpackEncoreBundle\WebpackEncoreBundle;
use SymfonyCasts\Bundle\ResetPassword\SymfonyCastsResetPasswordBundle;

final class NumberNineBundleKernel extends Kernel
{
    use MicroKernelTrait;

    public function __construct()
    {
        parent::__construct('dev', true);
    }

    public function registerBundles(): array
    {
        return [
            new FrameworkBundle(),
            new SecurityBundle(),
            new TwigBundle(),
            new CmfRoutingBundle(),
            new StofDoctrineExtensionsBundle(),
            new WebpackEncoreBundle(),
            new DoctrineBundle(),
            new DoctrineFixturesBundle(),
            new DoctrineMigrationsBundle(),
            new DAMADoctrineTestBundle(),
            new NumberNineBundle(),
            new NumberNineChapterOneBundle(),
            new SymfonyCastsResetPasswordBundle(),
            new FOSJsRoutingBundle(),
        ];
    }

    public function getCacheDir(): string
    {
        return __DIR__ . '/../../var/cache/dev/';
    }

    public function build(ContainerBuilder $container): void
    {
        parent::build($container); // TODO: Change the autogenerated stub
        $container->setParameter('kernel.secret', 'thisisnotreallyasecret');
    }

    protected function configureContainer(ContainerConfigurator $container): void
    {
        $container->import(__DIR__ . '/Resources/config/app.yaml');
        $container->import(__DIR__ . '/Resources/config/{app}_' . $this->environment . '.yaml');
        $container->import(__DIR__ . '/Resources/config/services.yaml');
    }

    protected function configureRoutes(RoutingConfigurator $routes): void
    {
        $routes->import(__DIR__ . '/Resources/config/routing.yaml');
    }
}
