security:
    enable_authenticator_manager: true

    password_hashers:
        NumberNine\Entity\User: auto

    providers:
        numbernine_user_provider:
            entity:
                class: NumberNine\Entity\User
                property: username

    firewalls:
        main:
            stateless: false
            lazy: true
            provider: numbernine_user_provider
            custom_authenticators:
                - NumberNine\Security\LoginFormAuthenticator
            logout:
                path: numbernine_logout
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 31536000 # 1 year in seconds
                path: /
            login_throttling:
                limiter: numbernine.login_rate_limiter

    access_control:
        - { path: ^/admin/login, role: PUBLIC_ACCESS }
        - { path: ^/admin/logout, role: PUBLIC_ACCESS }
        - { path: ^/admin/reset-password, role: PUBLIC_ACCESS }
        - { path: ^/admin/, allow_if: "is_granted('access_admin') and is_fully_authenticated()" }
        - { path: ^/, role: PUBLIC_ACCESS }

twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['@NumberNine/form/tailwind_layout.html.twig']

cmf_routing:
    chain:
        routers_by_id:
            router.default: 200
            cmf_routing.dynamic_router: 100
    dynamic:
        enabled: true
        route_provider_service_id: NumberNine\Routing\RouteProvider

stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            sluggable: true
            timestampable: true
            softdeleteable: true
            loggable: true

framework:
    profiler: { only_exceptions: false }
    cache:
        prefix_seed: ~
        pools:
            doctrine.metadata_cache_pool:
                adapter: cache.app
            doctrine.query_cache_pool:
                adapter: cache.app
            doctrine.result_cache_pool:
                adapter: cache.app
    assets:
        packages:
            numbernine:
                json_manifest_path: '%kernel.project_dir%/public/bundles/numbernine/build/manifest.json'
    session:
        handler_id: ~
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
    rate_limiter:
        username_ip_login:
            policy: token_bucket
            limit: 5
            rate:
                interval: '5 minutes'
        ip_login:
            policy: sliding_window
            limit: 50
            interval: '15 minutes'

webpack_encore:
    output_path: '%kernel.project_dir%/public/build'
    preload: true
    builds:
        numbernine: '%kernel.project_dir%/public/bundles/numbernine/build/'
    script_attributes:
        defer: true
        'data-turbo-track': reload
    link_attributes:
        'data-turbo-track': reload

doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        metadata_cache_driver:
            type: pool
            pool: doctrine.metadata_cache_pool
        query_cache_driver:
            type: pool
            pool: doctrine.query_cache_pool
        result_cache_driver:
            type: pool
            pool: doctrine.result_cache_pool
        #        second_level_cache:
        #            enabled: true
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
        dql:
            string_functions:
                JSON_EXTRACT: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonExtract
                JSON_CONTAINS: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonContains
                JSON_SEARCH: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonSearch
                JSON_KEYS: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonKeys
                CAST: DoctrineExtensions\Query\Mysql\Cast
                LEAST: DoctrineExtensions\Query\Mysql\Least
                REGEXP_REPLACE: DoctrineExtensions\Query\Postgresql\RegexpReplace
        mappings:
            gedmo_loggable:
                type: annotation
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Loggable/Entity"
                alias: GedmoLoggable
                is_bundle: false

symfonycasts_reset_password:
    request_password_repository: NumberNine\Repository\ResetPasswordRequestRepository
