services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            string $projectPath: '%kernel.project_dir%'

    NumberNine\Tests\TestServices\TestTemplatesTwigLoader: ~
    NumberNine\Tests\TestServices\SampleShortcode: ~
