services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            string $projectPath: '%kernel.project_dir%'

    NumberNine\Tests\Dummy\Twig\Loader\TestTemplatesTwigLoader: ~
    NumberNine\Tests\Dummy\Shortcode\SampleShortcode: ~
