services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    NumberNine\Tests\Dummy\Twig\Loader\TestTemplatesTwigLoader:
        arguments:
            $projectPath: '%kernel.project_dir%'
    NumberNine\Tests\Dummy\Shortcode\SampleShortcode: ~
