security:
    password_hashers:
        NumberNine\Entity\User:
            algorithm: auto
            cost: 4

framework:
    test: true
    secret: F00
    session:
        storage_factory_id: session.storage.factory.mock_file

doctrine:
    dbal:
        url: "%env(resolve:DATABASE_URL)%"

monolog:
    handlers:
        main:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            max_files: 1
