controllers:
    resource: ../src/Controller/
    type: annotation

admin_controllers:
    resource: '../src/Controller/Admin/**/*'
    type: annotation
    prefix: /%numbernine.config.admin_url_prefix%
    exclude: '../src/Controller/Admin/Security/ResetPasswordController.php'

admin_api_controllers:
    resource: ../src/Controller/Admin/Api
    type: annotation
    prefix: /%numbernine.config.admin_url_prefix%/api
