# Routes are generated in NumberNine\EventSubscriber\RougeRegistrationEventSubscriber
menus:
    dashboard:
        text: Dashboard
        route: numbernine_admin_index
        icon: tachometer-alt
    media_library:
        text: Media Library
        link: /media/
        icon: photo-video
    #    forms:
    #        text: Forms
    #        route:
    #        icon: mdi-form-dropdown
    #        children:
    #            all:
    #                text: All forms
    #                link: /forms/
    #            add_new:
    #                text: Add new
    #                link: /forms/new
    users:
        text: Users
        route:
        icon: users
        children:
            all:
                text: All users
                link: /users/
            add_new:
                text: Add new
                link: /users/new
            roles:
                text: Roles
                link: /users/roles/
    settings:
        text: Settings
        route:
        icon: cogs
        children:
            general:
                text: General
                route: numbernine_admin_settings_general
            permalinks:
                text: Permalinks
                route: numbernine_admin_settings_permalinks
            email:
                text: Emails
                link: /settings/emails/
    appearance:
        text: Appearance
        route:
        icon: paint-brush
        children:
            customize:
                text: Customize
                link: /customizer/
            menus:
                text: Menus
                link: /menus/
