# Routes are generated in NumberNine\EventSubscriber\RougeRegistrationEventSubscriber
menus:
    dashboard:
        text: Dashboard
        route: numbernine_admin_index
        icon: tachometer-alt
    media_library:
        text: Media Library
        route: numbernine_admin_media_library_index
        icon: photo-video
        if_granted: edit_media_files
    #    forms:
    #        text: Forms
    #        route:
    #        icon: mdi-form-dropdown
    #        children:
    #            all:
    #                text: All forms
    #                link: /forms/
    #            add_new:
    #                text: Add new
    #                link: /forms/new
    users:
        text: Users
        route: numbernine_admin_user_index
        icon: users
        if_granted: list_users
        children:
            all:
                text: All users
                route: numbernine_admin_user_index
            add_new:
                text: Add new
                route: numbernine_admin_user_create
                if_granted: create_users
            roles:
                text: Roles
                route: numbernine_admin_user_role_index
                if_granted: manage_roles
    settings:
        text: Settings
        route:
        icon: cogs
        if_granted: manage_options
        children:
            general:
                text: General
                route: numbernine_admin_settings_general
            permalinks:
                text: Permalinks
                route: numbernine_admin_settings_permalinks
            email:
                text: Emails
                route: numbernine_admin_settings_emails
    appearance:
        text: Appearance
        route:
        icon: paint-brush
        if_granted: customize
        children:
            areas:
                text: Areas
                route: numbernine_admin_area_page_builder_index
            menus:
                text: Menus
                route: numbernine_admin_menu_index
